% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 16-Nov-2015 19:39:47
%  MATLAB version: 8.0.0.783 (R2012b)
% -------------------------------------------------------------------


keyCycle_tKeyOffDelay_val = EcoObj.Parameter;
keyCycle_tKeyOffDelay_val.Value = 5;
keyCycle_tKeyOffDelay_val.RTWInfo.Alias = '';
keyCycle_tKeyOffDelay_val.RTWInfo.Alias = '';
keyCycle_tKeyOffDelay_val.Description = '';
keyCycle_tKeyOffDelay_val.RTWInfo.CustomStorageClass = 'Calibration';
keyCycle_tKeyOffDelay_val.Description = '';
  %%;
keyCycle_tKeyOffDelay_val.Description = '';
keyCycle_tKeyOffDelay_val.Description = '';
keyCycle_tKeyOffDelay_val.DataType = 'single';
keyCycle_tKeyOffDelay_val.Description = '';
keyCycle_tKeyOffDelay_val.Description = '';
keyCycle_tKeyOffDelay_val.DocUnits = 's';

keyCycle_flgResetSWEn_val = EcoObj.Parameter;
keyCycle_flgResetSWEn_val.Value = 1;
keyCycle_flgResetSWEn_val.RTWInfo.Alias = '';
keyCycle_flgResetSWEn_val.RTWInfo.Alias = '';
keyCycle_flgResetSWEn_val.Description = '';
keyCycle_flgResetSWEn_val.RTWInfo.CustomStorageClass = 'Calibration';
keyCycle_flgResetSWEn_val.Description = '';
  %%;
keyCycle_flgResetSWEn_val.Description = '';
keyCycle_flgResetSWEn_val.Description = '';
keyCycle_flgResetSWEn_val.DataType = 'boolean';
keyCycle_flgResetSWEn_val.Description = '';
keyCycle_flgResetSWEn_val.Description = '';
keyCycle_flgResetSWEn_val.DocUnits = '';

keyCycle_tDbncKeyOffFall_val = EcoObj.Parameter;
keyCycle_tDbncKeyOffFall_val.Value = 0.1;
keyCycle_tDbncKeyOffFall_val.RTWInfo.Alias = '';
keyCycle_tDbncKeyOffFall_val.RTWInfo.Alias = '';
keyCycle_tDbncKeyOffFall_val.Description = '';
keyCycle_tDbncKeyOffFall_val.RTWInfo.CustomStorageClass = 'Calibration';
keyCycle_tDbncKeyOffFall_val.Description = '';
  %%;
keyCycle_tDbncKeyOffFall_val.Description = '';
keyCycle_tDbncKeyOffFall_val.Description = '';
keyCycle_tDbncKeyOffFall_val.DataType = 'single';
keyCycle_tDbncKeyOffFall_val.Description = '';
keyCycle_tDbncKeyOffFall_val.Description = '';
keyCycle_tDbncKeyOffFall_val.DocUnits = 's';

keyCycle_tDbncKeyOffRise_val = EcoObj.Parameter;
keyCycle_tDbncKeyOffRise_val.Value = 0.1;
keyCycle_tDbncKeyOffRise_val.RTWInfo.Alias = '';
keyCycle_tDbncKeyOffRise_val.RTWInfo.Alias = '';
keyCycle_tDbncKeyOffRise_val.Description = '';
keyCycle_tDbncKeyOffRise_val.RTWInfo.CustomStorageClass = 'Calibration';
keyCycle_tDbncKeyOffRise_val.Description = '';
  %%;
keyCycle_tDbncKeyOffRise_val.Description = '';
keyCycle_tDbncKeyOffRise_val.Description = '';
keyCycle_tDbncKeyOffRise_val.DataType = 'single';
keyCycle_tDbncKeyOffRise_val.Description = '';
keyCycle_tDbncKeyOffRise_val.Description = '';
keyCycle_tDbncKeyOffRise_val.DocUnits = 's';


keyCycle_uKeyOnHyst_val = EcoObj.Parameter;
keyCycle_uKeyOnHyst_val.Value = 2;
keyCycle_uKeyOnHyst_val.RTWInfo.Alias = '';
keyCycle_uKeyOnHyst_val.RTWInfo.Alias = '';
keyCycle_uKeyOnHyst_val.Description = '';
keyCycle_uKeyOnHyst_val.RTWInfo.CustomStorageClass = 'Calibration';
keyCycle_uKeyOnHyst_val.Description = '';
  %%;
keyCycle_uKeyOnHyst_val.Description = '';
keyCycle_uKeyOnHyst_val.Description = '';
keyCycle_uKeyOnHyst_val.DataType = 'single';
keyCycle_uKeyOnHyst_val.Description = '';
keyCycle_uKeyOnHyst_val.Description = '';
keyCycle_uKeyOnHyst_val.DocUnits = 'V';

keyCycle_uKeyOffThr_val = EcoObj.Parameter;
keyCycle_uKeyOffThr_val.Value = 6;
keyCycle_uKeyOffThr_val.RTWInfo.Alias = '';
keyCycle_uKeyOffThr_val.RTWInfo.Alias = '';
keyCycle_uKeyOffThr_val.Description = '';
keyCycle_uKeyOffThr_val.RTWInfo.CustomStorageClass = 'Calibration';
keyCycle_uKeyOffThr_val.Description = '';
  %%;
keyCycle_uKeyOffThr_val.Description = '';
keyCycle_uKeyOffThr_val.Description = '';
keyCycle_uKeyOffThr_val.DataType = 'single';
keyCycle_uKeyOffThr_val.Description = '';
keyCycle_uKeyOffThr_val.Description = '';
keyCycle_uKeyOffThr_val.DocUnits = 'V';
