function FlexRayDefStruct=FlexRay_Params_Node1()

FlexRayParamsConfig1;

lenStatic=FlexRayDefStruct.network_para.gPayloadLengthStatic;
FlexRayDefStruct.MsgList={...
    struct('name', {'VCUStartupFrame'},'id', hex2dec('1'),'direction', 1,'length', lenStatic,'cycle', 0,'startupFrame',1,'syncFrame',1,'transMode',0), ...
    struct('name', {'rxVCU1'},'id', hex2dec('2'),'direction', 0,'length', lenStatic,'cycle',0,'startupFrame',0,'syncFrame',0,'transMode',0), ...
    struct('name', {'rxVCU2'},'id', hex2dec('3B'),'direction', 0,'length',lenStatic,'cycle',0,'startupFrame',0,'syncFrame',0,'transMode',0), ...
    struct('name', {'rxVCU3'},'id', hex2dec('3C'),'direction', 0,'length', lenStatic,'cycle',0,'startupFrame',0,'syncFrame',0,'transMode',0), ...
    struct('name', {'rxVCU4'},'id', hex2dec('3D'),'direction', 0,'length',2,'cycle',1,'startupFrame',0,'syncFrame',0,'transMode',0), ...
    struct('name', {'rxVCU5'},'id', hex2dec('3E'),'direction', 0,'length',4,'cycle',2,'startupFrame',0,'syncFrame',0,'transMode',0), ...
    struct('name', {'rxVCU6'},'id', hex2dec('47'),'direction', 0,'length',1,'cycle',3,'startupFrame',0,'syncFrame',0,'transMode',1), ...
  struct('name', {'S_M_0x5'},'id', hex2dec('5'),'direction', 1,'length', lenStatic,'cycle',0,'startupFrame',0,'syncFrame',0,'transMode',0), ...
  struct('name', {'S_M_0x6'},'id', hex2dec('6'),'direction', 0,'length', lenStatic,'cycle',0,'startupFrame',0,'syncFrame',0,'transMode',0), ...
  struct('name', {'D_M_0x41'},'id', hex2dec('41'),'direction', 1,'length', 19,'cycle',20,'startupFrame',0,'syncFrame',0,'transMode',0), ...
  struct('name', {'D_M_0x42'},'id', hex2dec('42'),'direction', 0,'length', 19,'cycle',20,'startupFrame',0,'syncFrame',0,'transMode',0), ...
};



%assignin( 'base', 'EcoCoderFlexRayDefStruct', FlexRayDefStruct);
end