function NVMList=Test_FNVM_MX()
NVMList={...
    struct('name', {'FnvmI_double'},'type', {'double'},'size', hex2dec('80'),'init', 1,'value',EcoCoder_GenArrayValue(hex2dec('80'),0,1)), ...
    struct('name', {'FnvmI_single'},'type', {'single'},'size', hex2dec('80'),'init', 1,'value',EcoCoder_GenArrayValue(hex2dec('80'),0,1)), ...
    struct('name', {'FnvmI_4byte'},'type', {'int32'},'size', hex2dec('80'),'init', 1,'value',EcoCoder_GenArrayValue(hex2dec('80'),0,1)), ...
    struct('name', {'Fnvm_double'},'type', {'double'},'size', hex2dec('80'),'init', 0,'value',EcoCoder_GenArrayValue(hex2dec('80'),0,1)), ...
    struct('name', {'Fnvm_single'},'type', {'single'},'size', hex2dec('80'),'init', 0,'value',EcoCoder_GenArrayValue(hex2dec('80'),0,1)), ...
    struct('name', {'Fnvm_4byte'},'type', {'int32'},'size', hex2dec('80'),'init', 0,'value',EcoCoder_GenArrayValue(hex2dec('80'),0,1)), ...
};
end