% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 21-Apr-2016 14:15:26
%  MATLAB version: 8.1.0.604 (R2013a)
% -------------------------------------------------------------------
                                   

Test_dcOPWM1 = EcoObj.Parameter;
Test_dcOPWM1.Value = 50;
Test_dcOPWM1.RTWInfo.Alias = '';
Test_dcOPWM1.RTWInfo.Alias = '';
Test_dcOPWM1.RTWInfo.Alias = '';
Test_dcOPWM1.RTWInfo.CustomStorageClass = 'Calibration';
Test_dcOPWM1.Description = '';
Test_dcOPWM1.RTWInfo.CustomAttributes.HeaderFile = '';
Test_dcOPWM1.Description = '';
Test_dcOPWM1.DataType = 'fixdt(0,16,1/100,0)';
Test_dcOPWM1.Description = '';
Test_dcOPWM1.Description = '';
Test_dcOPWM1.DocUnits = '%';

Test_dcOPWM2 = EcoObj.Parameter;
Test_dcOPWM2.Value = 50;
Test_dcOPWM2.RTWInfo.Alias = '';
Test_dcOPWM2.RTWInfo.Alias = '';
Test_dcOPWM2.RTWInfo.Alias = '';
Test_dcOPWM2.RTWInfo.CustomStorageClass = 'Calibration';
Test_dcOPWM2.Description = '';
Test_dcOPWM2.RTWInfo.CustomAttributes.HeaderFile = '';
Test_dcOPWM2.Description = '';
Test_dcOPWM2.DataType = 'fixdt(0,16,1/100,0)';
Test_dcOPWM2.Description = '';
Test_dcOPWM2.Description = '';
Test_dcOPWM2.DocUnits = '%';

Test_dcOPWM3 = EcoObj.Parameter;
Test_dcOPWM3.Value = 50;
Test_dcOPWM3.RTWInfo.Alias = '';
Test_dcOPWM3.RTWInfo.Alias = '';
Test_dcOPWM3.RTWInfo.Alias = '';
Test_dcOPWM3.RTWInfo.CustomStorageClass = 'Calibration';
Test_dcOPWM3.Description = '';
Test_dcOPWM3.RTWInfo.CustomAttributes.HeaderFile = '';
Test_dcOPWM3.Description = '';
Test_dcOPWM3.DataType = 'fixdt(0,16,1/100,0)';
Test_dcOPWM3.Description = '';
Test_dcOPWM3.Description = '';
Test_dcOPWM3.DocUnits = '%';

Test_dcOPWM4 = EcoObj.Parameter;
Test_dcOPWM4.Value = 50;
Test_dcOPWM4.RTWInfo.Alias = '';
Test_dcOPWM4.RTWInfo.Alias = '';
Test_dcOPWM4.RTWInfo.Alias = '';
Test_dcOPWM4.RTWInfo.CustomStorageClass = 'Calibration';
Test_dcOPWM4.Description = '';
Test_dcOPWM4.RTWInfo.CustomAttributes.HeaderFile = '';
Test_dcOPWM4.Description = '';
Test_dcOPWM4.DataType = 'fixdt(0,16,1/100,0)';
Test_dcOPWM4.Description = '';
Test_dcOPWM4.Description = '';
Test_dcOPWM4.DocUnits = '%';

Test_dcOPWM5 = EcoObj.Parameter;
Test_dcOPWM5.Value = 50;
Test_dcOPWM5.RTWInfo.Alias = '';
Test_dcOPWM5.RTWInfo.Alias = '';
Test_dcOPWM5.RTWInfo.Alias = '';
Test_dcOPWM5.RTWInfo.CustomStorageClass = 'Calibration';
Test_dcOPWM5.Description = '';
Test_dcOPWM5.RTWInfo.CustomAttributes.HeaderFile = '';
Test_dcOPWM5.Description = '';
Test_dcOPWM5.DataType = 'fixdt(0,16,1/100,0)';
Test_dcOPWM5.Description = '';
Test_dcOPWM5.Description = '';
Test_dcOPWM5.DocUnits = '%';

Test_dcOPWM6 = EcoObj.Parameter;
Test_dcOPWM6.Value = 50;
Test_dcOPWM6.RTWInfo.Alias = '';
Test_dcOPWM6.RTWInfo.Alias = '';
Test_dcOPWM6.RTWInfo.Alias = '';
Test_dcOPWM6.RTWInfo.CustomStorageClass = 'Calibration';
Test_dcOPWM6.Description = '';
Test_dcOPWM6.RTWInfo.CustomAttributes.HeaderFile = '';
Test_dcOPWM6.Description = '';
Test_dcOPWM6.DataType = 'fixdt(0,16,1/100,0)';
Test_dcOPWM6.Description = '';
Test_dcOPWM6.Description = '';
Test_dcOPWM6.DocUnits = '%';

Test_dcOPWM7 = EcoObj.Parameter;
Test_dcOPWM7.Value = 50;
Test_dcOPWM7.RTWInfo.Alias = '';
Test_dcOPWM7.RTWInfo.Alias = '';
Test_dcOPWM7.RTWInfo.Alias = '';
Test_dcOPWM7.RTWInfo.CustomStorageClass = 'Calibration';
Test_dcOPWM7.Description = '';
Test_dcOPWM7.RTWInfo.CustomAttributes.HeaderFile = '';
Test_dcOPWM7.Description = '';
Test_dcOPWM7.DataType = 'fixdt(0,16,1/100,0)';
Test_dcOPWM7.Description = '';
Test_dcOPWM7.Description = '';
Test_dcOPWM7.DocUnits = '%';


Test_frqOPWM1 = EcoObj.Parameter;
Test_frqOPWM1.Value = 1000;
Test_frqOPWM1.RTWInfo.Alias = '';
Test_frqOPWM1.RTWInfo.Alias = '';
Test_frqOPWM1.RTWInfo.Alias = '';
Test_frqOPWM1.RTWInfo.CustomStorageClass = 'Calibration';
Test_frqOPWM1.Description = '';
Test_frqOPWM1.RTWInfo.CustomAttributes.HeaderFile = '';
Test_frqOPWM1.Description = '';
Test_frqOPWM1.DataType = 'uint32';
Test_frqOPWM1.Description = '';
Test_frqOPWM1.Description = '';
Test_frqOPWM1.DocUnits = 'Hz';

Test_frqOPWM2 = EcoObj.Parameter;
Test_frqOPWM2.Value = 1000;
Test_frqOPWM2.RTWInfo.Alias = '';
Test_frqOPWM2.RTWInfo.Alias = '';
Test_frqOPWM2.RTWInfo.Alias = '';
Test_frqOPWM2.RTWInfo.CustomStorageClass = 'Calibration';
Test_frqOPWM2.Description = '';
Test_frqOPWM2.RTWInfo.CustomAttributes.HeaderFile = '';
Test_frqOPWM2.Description = '';
Test_frqOPWM2.DataType = 'uint32';
Test_frqOPWM2.Description = '';
Test_frqOPWM2.Description = '';
Test_frqOPWM2.DocUnits = 'Hz';

Test_frqOPWM3 = EcoObj.Parameter;
Test_frqOPWM3.Value = 1000;
Test_frqOPWM3.RTWInfo.Alias = '';
Test_frqOPWM3.RTWInfo.Alias = '';
Test_frqOPWM3.RTWInfo.Alias = '';
Test_frqOPWM3.RTWInfo.CustomStorageClass = 'Calibration';
Test_frqOPWM3.Description = '';
Test_frqOPWM3.RTWInfo.CustomAttributes.HeaderFile = '';
Test_frqOPWM3.Description = '';
Test_frqOPWM3.DataType = 'uint32';
Test_frqOPWM3.Description = '';
Test_frqOPWM3.Description = '';
Test_frqOPWM3.DocUnits = 'Hz';

Test_frqOPWM4 = EcoObj.Parameter;
Test_frqOPWM4.Value = 1000;
Test_frqOPWM4.RTWInfo.Alias = '';
Test_frqOPWM4.RTWInfo.Alias = '';
Test_frqOPWM4.RTWInfo.Alias = '';
Test_frqOPWM4.RTWInfo.CustomStorageClass = 'Calibration';
Test_frqOPWM4.Description = '';
Test_frqOPWM4.RTWInfo.CustomAttributes.HeaderFile = '';
Test_frqOPWM4.Description = '';
Test_frqOPWM4.DataType = 'uint32';
Test_frqOPWM4.Description = '';
Test_frqOPWM4.Description = '';
Test_frqOPWM4.DocUnits = 'Hz';

Test_frqOPWM5 = EcoObj.Parameter;
Test_frqOPWM5.Value = 1000;
Test_frqOPWM5.RTWInfo.Alias = '';
Test_frqOPWM5.RTWInfo.Alias = '';
Test_frqOPWM5.RTWInfo.Alias = '';
Test_frqOPWM5.RTWInfo.CustomStorageClass = 'Calibration';
Test_frqOPWM5.Description = '';
Test_frqOPWM5.RTWInfo.CustomAttributes.HeaderFile = '';
Test_frqOPWM5.Description = '';
Test_frqOPWM5.DataType = 'uint32';
Test_frqOPWM5.Description = '';
Test_frqOPWM5.Description = '';
Test_frqOPWM5.DocUnits = 'Hz';

Test_frqOPWM6 = EcoObj.Parameter;
Test_frqOPWM6.Value = 1000;
Test_frqOPWM6.RTWInfo.Alias = '';
Test_frqOPWM6.RTWInfo.Alias = '';
Test_frqOPWM6.RTWInfo.Alias = '';
Test_frqOPWM6.RTWInfo.CustomStorageClass = 'Calibration';
Test_frqOPWM6.Description = '';
Test_frqOPWM6.RTWInfo.CustomAttributes.HeaderFile = '';
Test_frqOPWM6.Description = '';
Test_frqOPWM6.DataType = 'uint32';
Test_frqOPWM6.Description = '';
Test_frqOPWM6.Description = '';
Test_frqOPWM6.DocUnits = 'Hz';

Test_frqOPWM7 = EcoObj.Parameter;
Test_frqOPWM7.Value = 1000;
Test_frqOPWM7.RTWInfo.Alias = '';
Test_frqOPWM7.RTWInfo.Alias = '';
Test_frqOPWM7.RTWInfo.Alias = '';
Test_frqOPWM7.RTWInfo.CustomStorageClass = 'Calibration';
Test_frqOPWM7.Description = '';
Test_frqOPWM7.RTWInfo.CustomAttributes.HeaderFile = '';
Test_frqOPWM7.Description = '';
Test_frqOPWM7.DataType = 'uint32';
Test_frqOPWM7.Description = '';
Test_frqOPWM7.Description = '';
Test_frqOPWM7.DocUnits = 'Hz';


