% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 28-Oct-2016 09:02:26
%  MATLAB version: 8.0.0.783 (R2012b)
% -------------------------------------------------------------------
                                     

CANB_flgStart = EcoObj.Signal;
CANB_flgStart.RTWInfo.Alias = '';
CANB_flgStart.RTWInfo.Alias = '';
CANB_flgStart.RTWInfo.Alias = '';
CANB_flgStart.RTWInfo.CustomStorageClass = 'Measurement';
CANB_flgStart.RTWInfo.CustomAttributes.HeaderFile = '';
CANB_flgStart.Description = '';
CANB_flgStart.DataType = 'boolean';
CANB_flgStart.Description = '';
CANB_flgStart.Description = '';
CANB_flgStart.DocUnits = '';
CANB_flgStart.Dimensions = 1;
CANB_flgStart.DimensionsMode = 'Fixed';
CANB_flgStart.Complexity = 'real';
CANB_flgStart.SampleTime = -1;
CANB_flgStart.SamplingMode = 'Sample based';
CANB_flgStart.InitialValue = '';

CANB_flgStart_val = EcoObj.Parameter;
CANB_flgStart_val.Value = 0;
CANB_flgStart_val.RTWInfo.Alias = '';
CANB_flgStart_val.RTWInfo.Alias = '';
CANB_flgStart_val.RTWInfo.Alias = '';
CANB_flgStart_val.RTWInfo.CustomStorageClass = 'Calibration';
CANB_flgStart_val.RTWInfo.CustomAttributes.HeaderFile = '';
CANB_flgStart_val.Description = '';
CANB_flgStart_val.DataType = 'boolean';
CANB_flgStart_val.Description = '';
CANB_flgStart_val.Description = '';
CANB_flgStart_val.DocUnits = '';

CANB_nTxOnce = EcoObj.Signal;
CANB_nTxOnce.RTWInfo.Alias = '';
CANB_nTxOnce.RTWInfo.Alias = '';
CANB_nTxOnce.RTWInfo.Alias = '';
CANB_nTxOnce.RTWInfo.CustomStorageClass = 'Measurement';
CANB_nTxOnce.RTWInfo.CustomAttributes.HeaderFile = '';
CANB_nTxOnce.Description = '';
CANB_nTxOnce.DataType = 'uint8';
CANB_nTxOnce.Description = '';
CANB_nTxOnce.Description = '';
CANB_nTxOnce.DocUnits = '';
CANB_nTxOnce.Dimensions = 1;
CANB_nTxOnce.DimensionsMode = 'Fixed';
CANB_nTxOnce.Complexity = 'real';
CANB_nTxOnce.SampleTime = -1;
CANB_nTxOnce.SamplingMode = 'Sample based';
CANB_nTxOnce.InitialValue = '';

CANB_nTxOnce_val = EcoObj.Parameter;
CANB_nTxOnce_val.Value = 20;
CANB_nTxOnce_val.RTWInfo.Alias = '';
CANB_nTxOnce_val.RTWInfo.Alias = '';
CANB_nTxOnce_val.RTWInfo.Alias = '';
CANB_nTxOnce_val.RTWInfo.CustomStorageClass = 'Calibration';
CANB_nTxOnce_val.RTWInfo.CustomAttributes.HeaderFile = '';
CANB_nTxOnce_val.Description = '';
CANB_nTxOnce_val.DataType = 'uint8';
CANB_nTxOnce_val.Description = '';
CANB_nTxOnce_val.Description = '';
CANB_nTxOnce_val.DocUnits = '';

CANB_nTxTimes = EcoObj.Signal;
CANB_nTxTimes.RTWInfo.Alias = '';
CANB_nTxTimes.RTWInfo.Alias = '';
CANB_nTxTimes.RTWInfo.Alias = '';
CANB_nTxTimes.RTWInfo.CustomStorageClass = 'Measurement';
CANB_nTxTimes.RTWInfo.CustomAttributes.HeaderFile = '';
CANB_nTxTimes.Description = '';
CANB_nTxTimes.DataType = 'uint16';
CANB_nTxTimes.Description = '';
CANB_nTxTimes.Description = '';
CANB_nTxTimes.DocUnits = '';
CANB_nTxTimes.Dimensions = 1;
CANB_nTxTimes.DimensionsMode = 'Fixed';
CANB_nTxTimes.Complexity = 'real';
CANB_nTxTimes.SampleTime = -1;
CANB_nTxTimes.SamplingMode = 'Sample based';
CANB_nTxTimes.InitialValue = '';

CANB_nTxTimes_val = EcoObj.Parameter;
CANB_nTxTimes_val.Value = 20;
CANB_nTxTimes_val.RTWInfo.Alias = '';
CANB_nTxTimes_val.RTWInfo.Alias = '';
CANB_nTxTimes_val.RTWInfo.Alias = '';
CANB_nTxTimes_val.RTWInfo.CustomStorageClass = 'Calibration';
CANB_nTxTimes_val.RTWInfo.CustomAttributes.HeaderFile = '';
CANB_nTxTimes_val.Description = '';
CANB_nTxTimes_val.DataType = 'uint16';
CANB_nTxTimes_val.Description = '';
CANB_nTxTimes_val.Description = '';
CANB_nTxTimes_val.DocUnits = '';

