% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 21-Apr-2016 14:42:51
%  MATLAB version: 8.1.0.604 (R2013a)
% -------------------------------------------------------------------
                                  

Test_tIPIT100ms = EcoObj.Signal;
Test_tIPIT100ms.RTWInfo.Alias = '';
Test_tIPIT100ms.RTWInfo.Alias = '';
Test_tIPIT100ms.RTWInfo.Alias = '';
Test_tIPIT100ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tIPIT100ms.Description = '';
Test_tIPIT100ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tIPIT100ms.Description = '';
Test_tIPIT100ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tIPIT100ms.Description = '';
Test_tIPIT100ms.Description = '';
Test_tIPIT100ms.DocUnits = 'ms';
Test_tIPIT100ms.Dimensions = 1;
Test_tIPIT100ms.DimensionsMode = 'Fixed';
Test_tIPIT100ms.Complexity = 'real';
Test_tIPIT100ms.SampleTime = -1;
Test_tIPIT100ms.SamplingMode = 'Sample based';
Test_tIPIT100ms.InitialValue = '';

Test_tIPIT10ms = EcoObj.Signal;
Test_tIPIT10ms.RTWInfo.Alias = '';
Test_tIPIT10ms.RTWInfo.Alias = '';
Test_tIPIT10ms.RTWInfo.Alias = '';
Test_tIPIT10ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tIPIT10ms.Description = '';
Test_tIPIT10ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tIPIT10ms.Description = '';
Test_tIPIT10ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tIPIT10ms.Description = '';
Test_tIPIT10ms.Description = '';
Test_tIPIT10ms.DocUnits = 'ms';
Test_tIPIT10ms.Dimensions = 1;
Test_tIPIT10ms.DimensionsMode = 'Fixed';
Test_tIPIT10ms.Complexity = 'real';
Test_tIPIT10ms.SampleTime = -1;
Test_tIPIT10ms.SamplingMode = 'Sample based';
Test_tIPIT10ms.InitialValue = '';

Test_tIPIT1ms = EcoObj.Signal;
Test_tIPIT1ms.RTWInfo.Alias = '';
Test_tIPIT1ms.RTWInfo.Alias = '';
Test_tIPIT1ms.RTWInfo.Alias = '';
Test_tIPIT1ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tIPIT1ms.Description = '';
Test_tIPIT1ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tIPIT1ms.Description = '';
Test_tIPIT1ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tIPIT1ms.Description = '';
Test_tIPIT1ms.Description = '';
Test_tIPIT1ms.DocUnits = 'ms';
Test_tIPIT1ms.Dimensions = 1;
Test_tIPIT1ms.DimensionsMode = 'Fixed';
Test_tIPIT1ms.Complexity = 'real';
Test_tIPIT1ms.SampleTime = -1;
Test_tIPIT1ms.SamplingMode = 'Sample based';
Test_tIPIT1ms.InitialValue = '';

Test_tIPIT20ms = EcoObj.Signal;
Test_tIPIT20ms.RTWInfo.Alias = '';
Test_tIPIT20ms.RTWInfo.Alias = '';
Test_tIPIT20ms.RTWInfo.Alias = '';
Test_tIPIT20ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tIPIT20ms.Description = '';
Test_tIPIT20ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tIPIT20ms.Description = '';
Test_tIPIT20ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tIPIT20ms.Description = '';
Test_tIPIT20ms.Description = '';
Test_tIPIT20ms.DocUnits = 'ms';
Test_tIPIT20ms.Dimensions = 1;
Test_tIPIT20ms.DimensionsMode = 'Fixed';
Test_tIPIT20ms.Complexity = 'real';
Test_tIPIT20ms.SampleTime = -1;
Test_tIPIT20ms.SamplingMode = 'Sample based';
Test_tIPIT20ms.InitialValue = '';

Test_tIPIT5ms = EcoObj.Signal;
Test_tIPIT5ms.RTWInfo.Alias = '';
Test_tIPIT5ms.RTWInfo.Alias = '';
Test_tIPIT5ms.RTWInfo.Alias = '';
Test_tIPIT5ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tIPIT5ms.Description = '';
Test_tIPIT5ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tIPIT5ms.Description = '';
Test_tIPIT5ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tIPIT5ms.Description = '';
Test_tIPIT5ms.Description = '';
Test_tIPIT5ms.DocUnits = 'ms';
Test_tIPIT5ms.Dimensions = 1;
Test_tIPIT5ms.DimensionsMode = 'Fixed';
Test_tIPIT5ms.Complexity = 'real';
Test_tIPIT5ms.SampleTime = -1;
Test_tIPIT5ms.SamplingMode = 'Sample based';
Test_tIPIT5ms.InitialValue = '';

Test_tITask1000ms = EcoObj.Signal;
Test_tITask1000ms.RTWInfo.Alias = '';
Test_tITask1000ms.RTWInfo.Alias = '';
Test_tITask1000ms.RTWInfo.Alias = '';
Test_tITask1000ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask1000ms.Description = '';
Test_tITask1000ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask1000ms.Description = '';
Test_tITask1000ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask1000ms.Description = '';
Test_tITask1000ms.Description = '';
Test_tITask1000ms.DocUnits = 'ms';
Test_tITask1000ms.Dimensions = 1;
Test_tITask1000ms.DimensionsMode = 'Fixed';
Test_tITask1000ms.Complexity = 'real';
Test_tITask1000ms.SampleTime = -1;
Test_tITask1000ms.SamplingMode = 'Sample based';
Test_tITask1000ms.InitialValue = '';

Test_tITask100ms = EcoObj.Signal;
Test_tITask100ms.RTWInfo.Alias = '';
Test_tITask100ms.RTWInfo.Alias = '';
Test_tITask100ms.RTWInfo.Alias = '';
Test_tITask100ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask100ms.Description = '';
Test_tITask100ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask100ms.Description = '';
Test_tITask100ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask100ms.Description = '';
Test_tITask100ms.Description = '';
Test_tITask100ms.DocUnits = 'ms';
Test_tITask100ms.Dimensions = 1;
Test_tITask100ms.DimensionsMode = 'Fixed';
Test_tITask100ms.Complexity = 'real';
Test_tITask100ms.SampleTime = -1;
Test_tITask100ms.SamplingMode = 'Sample based';
Test_tITask100ms.InitialValue = '';

Test_tITask10ms = EcoObj.Signal;
Test_tITask10ms.RTWInfo.Alias = '';
Test_tITask10ms.RTWInfo.Alias = '';
Test_tITask10ms.RTWInfo.Alias = '';
Test_tITask10ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask10ms.Description = '';
Test_tITask10ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask10ms.Description = '';
Test_tITask10ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask10ms.Description = '';
Test_tITask10ms.Description = '';
Test_tITask10ms.DocUnits = 'ms';
Test_tITask10ms.Dimensions = 1;
Test_tITask10ms.DimensionsMode = 'Fixed';
Test_tITask10ms.Complexity = 'real';
Test_tITask10ms.SampleTime = -1;
Test_tITask10ms.SamplingMode = 'Sample based';
Test_tITask10ms.InitialValue = '';

Test_tITask1ms = EcoObj.Signal;
Test_tITask1ms.RTWInfo.Alias = '';
Test_tITask1ms.RTWInfo.Alias = '';
Test_tITask1ms.RTWInfo.Alias = '';
Test_tITask1ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask1ms.Description = '';
Test_tITask1ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask1ms.Description = '';
Test_tITask1ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask1ms.Description = '';
Test_tITask1ms.Description = '';
Test_tITask1ms.DocUnits = 'ms';
Test_tITask1ms.Dimensions = 1;
Test_tITask1ms.DimensionsMode = 'Fixed';
Test_tITask1ms.Complexity = 'real';
Test_tITask1ms.SampleTime = -1;
Test_tITask1ms.SamplingMode = 'Sample based';
Test_tITask1ms.InitialValue = '';

Test_tITask200ms = EcoObj.Signal;
Test_tITask200ms.RTWInfo.Alias = '';
Test_tITask200ms.RTWInfo.Alias = '';
Test_tITask200ms.RTWInfo.Alias = '';
Test_tITask200ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask200ms.Description = '';
Test_tITask200ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask200ms.Description = '';
Test_tITask200ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask200ms.Description = '';
Test_tITask200ms.Description = '';
Test_tITask200ms.DocUnits = 'ms';
Test_tITask200ms.Dimensions = 1;
Test_tITask200ms.DimensionsMode = 'Fixed';
Test_tITask200ms.Complexity = 'real';
Test_tITask200ms.SampleTime = -1;
Test_tITask200ms.SamplingMode = 'Sample based';
Test_tITask200ms.InitialValue = '';

Test_tITask20ms = EcoObj.Signal;
Test_tITask20ms.RTWInfo.Alias = '';
Test_tITask20ms.RTWInfo.Alias = '';
Test_tITask20ms.RTWInfo.Alias = '';
Test_tITask20ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask20ms.Description = '';
Test_tITask20ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask20ms.Description = '';
Test_tITask20ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask20ms.Description = '';
Test_tITask20ms.Description = '';
Test_tITask20ms.DocUnits = 'ms';
Test_tITask20ms.Dimensions = 1;
Test_tITask20ms.DimensionsMode = 'Fixed';
Test_tITask20ms.Complexity = 'real';
Test_tITask20ms.SampleTime = -1;
Test_tITask20ms.SamplingMode = 'Sample based';
Test_tITask20ms.InitialValue = '';

Test_tITask500ms = EcoObj.Signal;
Test_tITask500ms.RTWInfo.Alias = '';
Test_tITask500ms.RTWInfo.Alias = '';
Test_tITask500ms.RTWInfo.Alias = '';
Test_tITask500ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask500ms.Description = '';
Test_tITask500ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask500ms.Description = '';
Test_tITask500ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask500ms.Description = '';
Test_tITask500ms.Description = '';
Test_tITask500ms.DocUnits = 'ms';
Test_tITask500ms.Dimensions = 1;
Test_tITask500ms.DimensionsMode = 'Fixed';
Test_tITask500ms.Complexity = 'real';
Test_tITask500ms.SampleTime = -1;
Test_tITask500ms.SamplingMode = 'Sample based';
Test_tITask500ms.InitialValue = '';

Test_tITask50ms = EcoObj.Signal;
Test_tITask50ms.RTWInfo.Alias = '';
Test_tITask50ms.RTWInfo.Alias = '';
Test_tITask50ms.RTWInfo.Alias = '';
Test_tITask50ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask50ms.Description = '';
Test_tITask50ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask50ms.Description = '';
Test_tITask50ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask50ms.Description = '';
Test_tITask50ms.Description = '';
Test_tITask50ms.DocUnits = 'ms';
Test_tITask50ms.Dimensions = 1;
Test_tITask50ms.DimensionsMode = 'Fixed';
Test_tITask50ms.Complexity = 'real';
Test_tITask50ms.SampleTime = -1;
Test_tITask50ms.SamplingMode = 'Sample based';
Test_tITask50ms.InitialValue = '';

Test_tITask5ms = EcoObj.Signal;
Test_tITask5ms.RTWInfo.Alias = '';
Test_tITask5ms.RTWInfo.Alias = '';
Test_tITask5ms.RTWInfo.Alias = '';
Test_tITask5ms.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITask5ms.Description = '';
Test_tITask5ms.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITask5ms.Description = '';
Test_tITask5ms.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITask5ms.Description = '';
Test_tITask5ms.Description = '';
Test_tITask5ms.DocUnits = 'ms';
Test_tITask5ms.Dimensions = 1;
Test_tITask5ms.DimensionsMode = 'Fixed';
Test_tITask5ms.Complexity = 'real';
Test_tITask5ms.SampleTime = -1;
Test_tITask5ms.SamplingMode = 'Sample based';
Test_tITask5ms.InitialValue = '';

Test_tITaskInit = EcoObj.Signal;
Test_tITaskInit.RTWInfo.Alias = '';
Test_tITaskInit.RTWInfo.Alias = '';
Test_tITaskInit.RTWInfo.Alias = '';
Test_tITaskInit.RTWInfo.CustomStorageClass = 'Measurement';
Test_tITaskInit.Description = '';
Test_tITaskInit.RTWInfo.CustomAttributes.HeaderFile = '';
Test_tITaskInit.Description = '';
Test_tITaskInit.DataType = 'fixdt(0,32,1/150000,0)';
Test_tITaskInit.Description = '';
Test_tITaskInit.Description = '';
Test_tITaskInit.DocUnits = 'ms';
Test_tITaskInit.Dimensions = 1;
Test_tITaskInit.DimensionsMode = 'Fixed';
Test_tITaskInit.Complexity = 'real';
Test_tITaskInit.SampleTime = -1;
Test_tITaskInit.SamplingMode = 'Sample based';
Test_tITaskInit.InitialValue = '';

tout = [0; 0.2; 0.4; 0.60000000000000009; 0.8; 1; 1.2; 1.4; 1.5999999999999999; ...
        1.7999999999999998; 1.9999999999999998; 2.1999999999999997; 2.4; ...
        2.6; 2.8000000000000003; 3.0000000000000004; 3.2000000000000006; ...
        3.4000000000000008; 3.600000000000001; 3.8000000000000012; 4.0000000000000009; ...
        4.2000000000000011; 4.4000000000000012; 4.6000000000000014; 4.8000000000000016; ...
        5.0000000000000018; 5.200000000000002; 5.4000000000000021; 5.6000000000000023; ...
        5.8000000000000025; 6.0000000000000027; 6.2000000000000028; 6.400000000000003; ...
        6.6000000000000032; 6.8000000000000034; 7.0000000000000036; 7.2000000000000037; ...
        7.4000000000000039; 7.6000000000000041; 7.8000000000000043; 8.0000000000000036; ...
        8.2000000000000028; 8.4000000000000021; 8.6000000000000014; 8.8; ...
        9; 9.2; 9.3999999999999986; 9.5999999999999979; 9.7999999999999972; ...
        10];

