% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 28-Oct-2016 09:02:26
%  MATLAB version: 8.0.0.783 (R2012b)
% -------------------------------------------------------------------
                                     

CANA_flgStart = EcoObj.Signal;
CANA_flgStart.RTWInfo.Alias = '';
CANA_flgStart.RTWInfo.Alias = '';
CANA_flgStart.RTWInfo.Alias = '';
CANA_flgStart.RTWInfo.CustomStorageClass = 'Measurement';
CANA_flgStart.RTWInfo.CustomAttributes.HeaderFile = '';
CANA_flgStart.Description = '';
CANA_flgStart.DataType = 'boolean';
CANA_flgStart.Description = '';
CANA_flgStart.Description = '';
CANA_flgStart.DocUnits = '';
CANA_flgStart.Dimensions = 1;
CANA_flgStart.DimensionsMode = 'Fixed';
CANA_flgStart.Complexity = 'real';
CANA_flgStart.SampleTime = -1;
CANA_flgStart.SamplingMode = 'Sample based';
CANA_flgStart.InitialValue = '';

CANA_flgStart_val = EcoObj.Parameter;
CANA_flgStart_val.Value = 0;
CANA_flgStart_val.RTWInfo.Alias = '';
CANA_flgStart_val.RTWInfo.Alias = '';
CANA_flgStart_val.RTWInfo.Alias = '';
CANA_flgStart_val.RTWInfo.CustomStorageClass = 'Calibration';
CANA_flgStart_val.RTWInfo.CustomAttributes.HeaderFile = '';
CANA_flgStart_val.Description = '';
CANA_flgStart_val.DataType = 'boolean';
CANA_flgStart_val.Description = '';
CANA_flgStart_val.Description = '';
CANA_flgStart_val.DocUnits = '';

CANA_nTxOnce = EcoObj.Signal;
CANA_nTxOnce.RTWInfo.Alias = '';
CANA_nTxOnce.RTWInfo.Alias = '';
CANA_nTxOnce.RTWInfo.Alias = '';
CANA_nTxOnce.RTWInfo.CustomStorageClass = 'Measurement';
CANA_nTxOnce.RTWInfo.CustomAttributes.HeaderFile = '';
CANA_nTxOnce.Description = '';
CANA_nTxOnce.DataType = 'uint8';
CANA_nTxOnce.Description = '';
CANA_nTxOnce.Description = '';
CANA_nTxOnce.DocUnits = '';
CANA_nTxOnce.Dimensions = 1;
CANA_nTxOnce.DimensionsMode = 'Fixed';
CANA_nTxOnce.Complexity = 'real';
CANA_nTxOnce.SampleTime = -1;
CANA_nTxOnce.SamplingMode = 'Sample based';
CANA_nTxOnce.InitialValue = '';

CANA_nTxOnce_val = EcoObj.Parameter;
CANA_nTxOnce_val.Value = 20;
CANA_nTxOnce_val.RTWInfo.Alias = '';
CANA_nTxOnce_val.RTWInfo.Alias = '';
CANA_nTxOnce_val.RTWInfo.Alias = '';
CANA_nTxOnce_val.RTWInfo.CustomStorageClass = 'Calibration';
CANA_nTxOnce_val.RTWInfo.CustomAttributes.HeaderFile = '';
CANA_nTxOnce_val.Description = '';
CANA_nTxOnce_val.DataType = 'uint8';
CANA_nTxOnce_val.Description = '';
CANA_nTxOnce_val.Description = '';
CANA_nTxOnce_val.DocUnits = '';

CANA_nTxTimes = EcoObj.Signal;
CANA_nTxTimes.RTWInfo.Alias = '';
CANA_nTxTimes.RTWInfo.Alias = '';
CANA_nTxTimes.RTWInfo.Alias = '';
CANA_nTxTimes.RTWInfo.CustomStorageClass = 'Measurement';
CANA_nTxTimes.RTWInfo.CustomAttributes.HeaderFile = '';
CANA_nTxTimes.Description = '';
CANA_nTxTimes.DataType = 'uint16';
CANA_nTxTimes.Description = '';
CANA_nTxTimes.Description = '';
CANA_nTxTimes.DocUnits = '';
CANA_nTxTimes.Dimensions = 1;
CANA_nTxTimes.DimensionsMode = 'Fixed';
CANA_nTxTimes.Complexity = 'real';
CANA_nTxTimes.SampleTime = -1;
CANA_nTxTimes.SamplingMode = 'Sample based';
CANA_nTxTimes.InitialValue = '';

CANA_nTxTimes_val = EcoObj.Parameter;
CANA_nTxTimes_val.Value = 20;
CANA_nTxTimes_val.RTWInfo.Alias = '';
CANA_nTxTimes_val.RTWInfo.Alias = '';
CANA_nTxTimes_val.RTWInfo.Alias = '';
CANA_nTxTimes_val.RTWInfo.CustomStorageClass = 'Calibration';
CANA_nTxTimes_val.RTWInfo.CustomAttributes.HeaderFile = '';
CANA_nTxTimes_val.Description = '';
CANA_nTxTimes_val.DataType = 'uint16';
CANA_nTxTimes_val.Description = '';
CANA_nTxTimes_val.Description = '';
CANA_nTxTimes_val.DocUnits = '';

