pwrtrnTmc_trqCmd= EcoObj.Signal;
pwrtrnTmc_trqCmd.RTWInfo.Alias = '';
pwrtrnTmc_trqCmd.RTWInfo.Alias = '';
pwrtrnTmc_trqCmd.Description = '';
pwrtrnTmc_trqCmd.RTWInfo.CustomStorageClass = 'Measurement';
pwrtrnTmc_trqCmd.Description = '';
pwrtrnTmc_trqCmd.Description = '';
pwrtrnTmc_trqCmd.Description = '';
pwrtrnTmc_trqCmd.DataType = 'DT_trq_Sgl';
pwrtrnTmc_trqCmd.Description = '';
pwrtrnTmc_trqCmd.Description = '';
pwrtrnTmc_trqCmd.DocUnits = '';
pwrtrnTmc_trqCmd.Dimensions = -1;
pwrtrnTmc_trqCmd.Description = '';
pwrtrnTmc_trqCmd.Complexity = 'auto';
pwrtrnTmc_trqCmd.SampleTime = -1;
pwrtrnTmc_trqCmd.SamplingMode = 'auto';
pwrtrnTmc_trqCmd.InitialValue = '';

